### ISSUE TITLE
Is the ad hominem detection endpoint still available?

### ISSUE THREAD

**Issue by prios-Alex-Turk** [iPieter/G0B34a_knowledge_and_the_web#31]
When I run the server with
```
npm run serve
```
and submit something to the webpage, I receive the error:
```
Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at r._transmit (http://localhost:8080/stomp.js:8:2874)
    at r.send (http://localhost:8080/stomp.js:8:7481)
    at VueComponent.call (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-service/node_modules/vue-loader/lib/index.js?!./src/components/FallacyView.vue?vue&type=script&lang=js&:108:19)
    at click (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"ad3b3710-vue-loader-template"}!./node_modules/@vue/cli-service/node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/@vue/cli-service/node_modules/vue-loader/lib/index.js?!./src/components/FallacyView.vue?vue&type=template&id=75763181&:40:19)
    at invoker (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:2118:18)
    at HTMLButtonElement.fn._withTask.fn._withTask (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1903:17)
r._transmit @ stomp.js:8
r.send @ stomp.js:8
call @ FallacyView.vue?7f0a:120
click @ FallacyView.vue?77db:37
invoker @ vue.runtime.esm.js?2b0e:2119
fn._withTask.fn._withTask @ vue.runtime.esm.js?2b0e:1904
```

Is this because the server is no longer available? Is there any way to still get this project running?

**Comment by iPieter** [comment]
It seems that you are running only the frontend of this project. 

The repo has both frontend and backend code, all the instructions for starting the backend are also in the README normally. If this isn't the case, feel free to reopen the issue.  

Good luck and my appologies for the late reply.
